/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.CriaUserDAO;
import dao.TablesDAO;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;
import modelo.User;

/**
 *
 * @author erick
 */
public class TelaGerente extends javax.swing.JFrame {
    private User user;
    private Vector listaRadio = new Vector();
    private TablesDAO dao;
    private JRadioButton radioButton;
    
    
    public static void main(String[] args) throws SQLException {
        //User user =new User();
        //user.setHost("localhost");
       // user.setPorta("3306");
       // TelaGerente tela = new TelaGerente(user);
       // tela.setVisible(true);
    }
    
    
    public TelaGerente(User user) throws SQLException {
        initComponents();
        this.user = user;
        carregarRadioButtun();
    }
    
    private static class RadioRenderer implements ListCellRenderer{

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            JRadioButton radio = (JRadioButton) value;
            return radio;
        }
        
    }
    
    private void carregarRadioButtun() throws SQLException{
        listaTabelas.setCellRenderer(new RadioRenderer());
        dao = new TablesDAO(user);
        
        for (String col : dao.selecionar()) {
            JRadioButton radio = new JRadioButton(col.toString());
            grupo.add(radio);
            listaRadio.add(radio);
        }
        listaTabelas.setListData(listaRadio);
        listaTabelas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listaTabelas.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e){
                int index = listaTabelas.locationToIndex(e.getPoint());
                if (index != -1){
                    radioButton = (JRadioButton) listaTabelas.getModel().getElementAt(index);
                    //JOptionPane.showMessageDialog(null, radioButton.isSelected());
                    if (radioButton.isSelected() == false)
                        radioButton.setSelected(true);
                    else
                        radioButton.setSelected(false);                
                }
                repaint();
            }
        
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTabelas = new javax.swing.JList();
        btCancelar = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Gerente");

        listaTabelas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaTabelas);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 59, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        JRadioButton radio = null;
        
        for(int i=0; i < listaTabelas.getModel().getSize();i++){
            if(((JRadioButton)listaTabelas.getModel().getElementAt(i)).isSelected()){
                radio = (JRadioButton)listaTabelas.getModel().getElementAt(i);
                break;
            }    
         }
        user.setPrivilegio(radio.getText());
        CriaUserDAO dao = new CriaUserDAO();
        try {
            dao.privelegioGerente(user);
            JOptionPane.showMessageDialog(null, "Usuário criado com sucesso!!"
                            + " Privelégio: Gerente");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    public User getUser(){
        return user;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaTabelas;
    // End of variables declaration//GEN-END:variables
}
